### ISSUE TITLE
Missing of  set_config in jcopdl.callback

### ISSUE THREAD

**Issue by Thomaswalkerg** [WiraDKP/deep_learning#2]
Hi Team,

The set_config is unable to import using all the versions of JCOPDL library. It is throwing error. Please help this asap.

**Comment by WiraDKP** [comment]
Hi @Thomaswalkerg 
You don't need `set_config` in jcopdl 2.x, but you'll need it in jcopdl 1.x.
Hence, `ImportError: cannot import name 'set_config' from 'jcopdl.callback'`

It is always recommended to use the environment that I have provided in this repo as it is specifically designed for the course. It would not throw the error.

If you, however, would like to use your own environment and `set_config`
Please add jcopdl 1.x to your environment
```
jcopdl==1.1.10
```

or if you are using Colab, simply install it with
```
pip install "jcopdl<2.0"
```

Hope it helps
